Ralith/hypermine

- client/src/config.rs
- client/src/main.rs
- client/src/prediction.rs
- client/src/sim.rs
- common/src/lib.rs
- common/src/proto.rs
- server/src/lib.rs
- server/src/sim.rs
With these changes, the client transmits input at exactly the server's tickrate, and immediately predicts the results. To ensure motion remains smooth and controllable at low tickrates, the actual input sent is the *average* of inputs over the timestep, so e.g. briefly tapping forwards will always produce a consistent small amount of motion.
> Motion input prediction

- client/src/worldgen.rs
Per today's insight:
> If g is a homogeneous scalar field, then the following process will result in a homogeneous field f: for any node W with single descender a, let `f(W) = f(Wa) + (g(W) + g(Wa)) * R`
This change still relies on, for homogeneous scalar field `g(x)`, `g(x) % K` being a homogeneous scalar field. I feel like that's a pretty reasonable judgement, but I'd like @MagmaMcFry's sanity check.
> Worldgen fixes

- client/shaders/surface-extraction/emit.comp
- client/shaders/voxels.vert
- client/src/graphics/voxels/mod.rs
- client/src/graphics/voxels/surface.rs
- client/src/graphics/voxels/surface_extraction.rs
- client/src/graphics/voxels/tests.rs
30-50% reduction in CPU time spent recording voxel draws.
> Smuggle voxel chunk ID through indirect buffer

- Cargo.toml
- client/src/config.rs
- client/src/graphics/draw.rs
- client/src/graphics/gltf_mesh.rs
- client/src/graphics/meshes.rs
- client/src/graphics/mod.rs
- client/src/graphics/png_array.rs
- client/src/graphics/voxels/mod.rs
- client/src/graphics/voxels/surface.rs
- client/src/graphics/voxels/surface_extraction.rs
- client/src/loader.rs
- client/src/main.rs
- client/src/sim.rs
- client/src/worldgen.rs
- common/src/chunks.rs
- common/src/lib.rs
- common/src/lru_slab.rs
- common/src/sim_config.rs
Fixes #45, #46. Still TODO: async surface extraction, which seems to be the bottleneck on intel GPUs. Terrain gen CPU load seems insignificant once decoupled.
> Generate voxel chunks on-demand in a background thread

- client/src/graphics/mod.rs
- client/src/graphics/window.rs
An infinite far plane makes sense for rendering euclidean vertices,
but in the Beltrami-Klein model we've already mapped infinity into the
unit ball, so we were only using a tiny fraction of depth range.
Switch to a VR-ready interface while we're at it.
> Make effective use of available depth precision

- client/Cargo.toml
- client/benches/surface_extraction.rs
- client/shaders/surface-extraction/common.h
- client/shaders/surface-extraction/count.comp
- client/shaders/surface-extraction/emit.comp
- client/shaders/surface-extraction/prefix-sum.comp
- client/src/config.rs
- client/src/graphics/base.rs
- client/src/graphics/draw.rs
- client/src/graphics/mod.rs
- client/src/graphics/voxels/mod.rs
- client/src/graphics/voxels/surface_extraction.rs
- client/src/graphics/voxels/tests.rs
~10x speedup for surface extraction on Intel. Pop-in is now much less of an issue; we just need to fine tune view distance culling and it'll be a thing of the past.
Fixes #81.
> Benchmark and optimize surface extraction

- common/src/worldgen.rs
I could use the code review even if this doesn't make it in in this form.
The margins mean there are certain vertical layers which will very obviously not generate trees, but there's no quick-fix for that.
> Random trees

- client/src/graphics/fog.rs
- client/src/graphics/meshes.rs
- client/src/graphics/voxels/surface.rs
- client/src/graphics/voxels/surface_extraction.rs
- client/src/graphics/voxels/tests.rs
- client/src/graphics/window.rs
- client/src/loader.rs
- client/src/net.rs
- common/src/dodeca.rs
- common/src/math.rs
- common/src/terraingen.rs
- common/src/worldgen.rs
- server/src/config.rs
- server/src/lib.rs
- server/src/sim.rs
This pull request has four related changes, all simple things to improve quality of life:
- The input movement vector is capped at a maximum magnitude of 1 to prevent conflicts between the server and client from causing jitter.
- Rotation speed has been modified to no longer depend on framerate
- The mouse can now only be used to look around when it's captured, allowing for easier multitasking while the app is open.
- The mouse is automatically uncaptured when the window loses focus
> Introduce minor quality of life improvements for movement

- client/shaders/surface-extraction/surface.h
- client/src/graphics/base.rs
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/math.rs
These are things I found while studying the code base earlier. I believe that these changes are all correct and will make the code easier to understand, but, needless to say, please check my work before merging.
There is one actual code change as well, which is the reduction of an array size from 3 to 2 in `populate_shorter_neighbors_of_child`. The purpose of the change was to stay consistent with the documentation. This did not cause any bugs based on my manual testing.
> Fix outdated and incorrect code documentation (along with a minor code change)

- client/Cargo.toml
- client/src/lahar_deprecated/transfer.rs
- client/src/loader.rs
- client/src/main.rs
- client/src/net.rs
- common/Cargo.toml
- server/Cargo.toml
- server/src/lib.rs
- server/src/main.rs
This PR contains the following related changes:
- Upgrade tokio from 0.2.13 to 1.18.2
- Upgrade quinn from 0.6.1 to 0.8.3
- Upgrade rustls from 0.17.0 to 0.20.6
Due to non-backwards-compatible changes in the way quinn/rustls handles certificates, some logic in that area needed to change.
A few items still need to be completed before I'm fully comfortable merging this.
> Tokio and quinn upgrade

- common/src/codec.rs
There is currently a bug in `recv_whole` that allows `cursor` to overshoot `size_limit`, causing `recv_whole` to be able to keep receiving data indefinitely (until `buf.reserve` panics).
I was able to reproduce this bug by artificially reducing `size_limit` and using `println!` to see what's going on. Unfortunately, without making more major changes to `codec.rs`, I am unable to add unit tests, as there isn't an easy way to generate a `quinn::RecvStream` in a test context.
I'm not familiar with the `quinn` library, so it may now be possible to make `recv_whole` practically a one-liner, it which case it would probably make the most sense to do that refactor now instead of just fixing the bug.
The actual bug fix is in the assignment to `slice`. I believe the change to the `buf.reserve` call …
> Ensure that recv_whole respects size_limit

- client/src/graphics/window.rs
- client/src/lahar_deprecated/transfer.rs
- common/src/node.rs
I believe it makes sense to resolve new clippy warnings in a separate PR for a cleaner commit history, so hopefully, this PR does the trick.
The warning in `window.rs`, [clippy::borrow_deref_ref](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref), was straightforward.
In `transfer.rs`, there was a [clippy::type_complexity](https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity) warning, but I decided to suppress it, since the hope is to eventually replace this code entirely, and it should stay as faithful as possible to the old version of lahar unless there's an actual bug.
In `node.rs`, clippy suggested that I implement `Eq` based on [clippy::derive_partial_eq_without_eq](https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_e …
> Fix Clippy warnings introduced by Rust 1.63.0

- common/src/dodeca.rs
- common/src/graph.rs
- common/src/plane.rs
- common/src/worldgen.rs
This PR has a major breaking change in dodeca.rs's API. In chunk coordinates, 0 and 1 are swapped from how they were before. This has a few advantages:
- The origin in chunk coordinates is at the center of the Beltrami-Klein model, making the mapping of these coordinates to Hyperbolic space more intuitive.
- Relatedly, the chunk coordinates give an idea of how distorted we are from a Euclidean cube, as higher-magnitude chunk coordinates have higher distortion, and everything is nicely behaved near the origin.
- Collision math should be slightly simpler due to the above points.
A potentially notable disadvantage is that the origin of a node and the origin of a chunk no longer coincide. However, I believe this is minor.
A few other helpful features have been added to dodeca.rs
- `Side` has …
> Refactor dodeca.rs to make math easier to understand

- Cargo.toml
- client/Cargo.toml
- client/src/graphics/draw.rs
- client/src/graphics/voxels/mod.rs
- client/src/graphics/window.rs
- client/src/lib.rs
- client/src/metrics.rs
- client/src/sim.rs
- common/Cargo.toml
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/lib.rs
- common/src/math.rs
- common/src/plane.rs
- common/src/worldgen.rs
- server/Cargo.toml
- server/src/lib.rs
- server/src/sim.rs
This PR upgrades the following crates (comments in parentheses):
- metrics (complicated)
- ash-window (mechanical)
- hecs (mechanical)
- nalgebra (mechanical. Was blocked by [a performance regression in nalgebra](https://github.com/dimforge/nalgebra/issues/1139), but this has now been fixed.)
- winit (mechanical)
- approx (trivial)
- rand (trivial)
- rand_distr (trivial)
- rand_pcg (trivial)
- rcgen (trivial)
- tracing (trivial)
- tracing-subscriber (trivial, apart from changing "chrono" feature to "time")
- webpki (trivial)
- metrics-core (removed, not upgraded, since "metrics" no longer uses it)
One semi-unrelated change is adding `debug-assertions = true` in the top-level Cargo.toml. [Debug assertions are only enabled by default in non-optimized …
> Upgrade all dependencies mentioned by dependabot

- client/src/lahar_deprecated/staging.rs
- client/src/main.rs
- common/src/worldgen.rs
- server/src/main.rs
The most common warning was
```
the borrowed expression implements the required traits
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```
Apart from that, there were two warnings related to `&*device`, which were
```
deref which would be done by auto-deref
`#[warn(clippy::explicit_auto_deref)]` on by default
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
```
While touching the code, I also redefined `normal` in `generate_terrain` to require fewer calls to `unwrap`, since that change seems simple and non-controversial.
> Fix Clippy warnings introduced by Rust 1.65.0

- client/src/graphics/draw.rs
- client/src/graphics/frustum.rs
- client/src/graphics/voxels/mod.rs
- client/src/prediction.rs
- client/src/sim.rs
- common/src/dodeca.rs
- common/src/lib.rs
- common/src/math.rs
- common/src/plane.rs
- server/src/sim.rs
This PR makes the following changes to math.rs that will hopefully make it more convenient to work with. I believe these changes are useful on their own, but the main purpose is to prepare for collision-related changes:
- `math::translate` now requires Lorentz-normalized vectors. Also, it uses a more direct formula rather than composing two reflections. This should hopefully be more efficient, but additional efficiency can be gained by having a special hardcoded function for translating the origin to a particular point.
- `math::translate_along` now only takes a single vector parameter, whose magnitude is how far to translate. Most users of this function benefit from the simplification. For instance, the `sanitize_motion_input` function is much shorter. Internally, it has also been …
> Simplify a few functions in math.rs

- common/src/lib.rs
Windows terminals don't support these by default, leading to garbage in diagnostics.
> Disable ANSI colors on Windows

- client/src/graphics/draw.rs
- common/src/worldgen.rs
The two warnings being fixed are
- Casting a `u32` to a `u32` (https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast)
- using `.min(a).max(b)` instead of `.clamp(a, b)` (https://rust-lang.github.io/rust-clippy/master/index.html#manual_clamp)
> Fix clippy warnings for Rust 1.66.0

- client/Cargo.toml
- common/Cargo.toml
- server/Cargo.toml
As Hypermine is designed to work with the latest version of Rust, it also makes sense to upgrade to the latest edition as well. There are some borrow checker improvements between these two editions.
I tested this manually, and it still works as before. No changes are needed for 2021 edition compatibility.
> Upgrade to Rust 2021 edition

- client/src/graphics/draw.rs
- client/src/graphics/window.rs
- client/src/prediction.rs
- client/src/sim.rs
- common/src/character_controller.rs
- common/src/lib.rs
- common/src/proto.rs
- common/src/sim_config.rs
- server/src/lib.rs
- server/src/sim.rs
This PR does the following
- Adds persistent velocity and acceleration, which is off by default and can be toggled with "V".
- Puts player movement logic into `character_controller.rs` to separate it from the netcode and prediction logic.
- Various changes/refactors to make this separation of logic possible, some of which will likely need revision.
While I believe this PR is technically in a mergeable state, I do not have that much confidence in the current state of this PR and am definitely open to suggestions on how to improve the readability/maintainability of this code. I have the following specific concerns:
> Add persistent velocity as a step towards player physics

- client/Cargo.toml
- common/Cargo.toml
- common/src/character_controller.rs
- common/src/dodeca.rs
- common/src/math.rs
- common/src/terraingen.rs
- common/src/worldgen.rs
- server/Cargo.toml
To prevent requiring the server to send lots of data to the client, terrain generation should be run on both the server and the client separately. To avoid inconsistencies in terrain generation caused by differing implementations of transcendental functions, we use the `libm` library, which provides its own implementation of these functions.
> Use libm to help prevent future terrain generation consistency bugs

- client/src/graphics/draw.rs
- client/src/graphics/voxels/mod.rs
- client/src/sim.rs
- common/src/character_controller.rs
- common/src/node.rs
- common/src/traversal.rs
- server/src/sim.rs
Relying on the consistency of terrain-generation code between runs and between different computers, we have the server generate chunks in a smaller radius of nodes around the player. This, in addition to future changes, will allow the server to run code that depends on the current state of the world, such as collision checking, terrain modification, NPC spawns, etc.
As no code currently depends on this server-generated terrain, testing that these changes work as intended is not possible without additional code modification. However, even if this is broken, this should not result in any regressions, so to limit the scope of this PR, the lack of I believe the lack of testability is acceptable.
One minor concrete change this PR makes is that terrain generation for the client no longer …
> Allow the server to generate terrain instead of just the client

- client/src/graphics/window.rs
- client/src/lib.rs
- client/src/main.rs
- common/src/lib.rs
- common/src/worldgen.rs
- server/src/lib.rs
- server/src/main.rs
~~This PR fixes 5 instances of [needless_borrowed_reference](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrowed_reference) and 6 instances of [uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args).~~
This PR allows the [needless_borrowed_reference](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrowed_reference) lint and fixes 6 instances of [uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args).
> Fix clippy warnings for Rust 1.67.0

- client/src/graphics/voxels/mod.rs
- common/src/character_controller.rs
- common/src/chunk_collision.rs
- common/src/cursor.rs
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/graph_collision.rs
- common/src/lib.rs
- common/src/node.rs
- common/src/sim_config.rs
- common/src/worldgen.rs
- server/src/sim.rs
This PR adds collision detection logic. There is a `shape_cast` method in the `common::collision` module that answers the question of "How far can a sphere of a given radius move in a given direction, up to a given distance, before colliding with a voxel? Does it collide at all?" If there is a collision, it also finds the normal, which can be used for collision resolution.
For testing purposes, a basic form of collision resolution is also included with these changes. As long as noclip is disabled by pressing "V", if a character collides with a wall, it will stop. This has the advantage of simplicity, but it has the disadvantage of making walls "sticky", so smoother movement is planned in a future PR.
> Add initial sphere-voxel collision detection 

- client/src/graphics/draw.rs
- client/src/graphics/frustum.rs
- common/src/character_controller.rs
- common/src/chunk_collision.rs
As a follow-up to https://github.com/Ralith/hypermine/pull/262, this PR improves the collision resolution logic of the character so that it slides against walls instead of getting stuck against them.
Unfortunately, the precision of the original collision logic was insufficient to avoid noticeable artifacts made visible by the updated collision resolution logic, so this PR also tweaks this collision logic to use more numerically stable formulas at the cost of being (hopefully only slightly) less efficient for sphere/vertex collisions.
> Allow the character to slide against walls

- .github/workflows/package.yml
- .github/workflows/rust.yml
- Cargo.toml
- save/Cargo.toml
- save/benches/bench.rs
- save/gen-protos/Cargo.toml
- save/gen-protos/src/main.rs
- save/src/lib.rs
- save/src/protos.proto
- save/src/protos.rs
- save/tests/heavy.rs
- save/tests/tests.rs
This PR defines a stand-alone library with a simple API for persisting world state to disk, including both edited voxels and other entity states. It is motivated by these goals:
- Fast random reads to any spatial neighborhood, to allow streaming large saves (e.g. highly-edited worlds) on-demand for consistent performance
- Fast random writes of the same, allowing only modified parts of the world to be written when saving, minimizing gameplay disruption regardless of total save size
- Consistency even in the face of crashes or power loss
- Compactness, to support large worlds and minimize required disk I/O
- Forwards-compatibility to minimize the odds of old saves becoming unusable after an update
- Loose coupling with the rest of the game
The design space is large, and this proposal …
> Groundwork for saves

- common/src/node.rs
- common/src/world.rs
Fortunately, the most recent Rust update's new lints don't seem to have any real downsides.
> Derive Default to fix Rust 1.68.0 clippy lint

- save/benches/bench.rs
- save/src/lib.rs
- save/src/protos.proto
- save/src/protos.rs
- save/tests/heavy.rs
- save/tests/tests.rs
Allows e.g. entity movements to be persisted without rewriting up to 67.5KiB (for a full node of 12-voxel chunks, uncompressed).
We could take this a step further and store each chunk separately, but that might reduce read performance, and voxel edits are expected to be infrequent.
> Isolate entity and voxel data in saves

- common/Cargo.toml
- common/benches/bench.rs
- common/src/graph.rs
- server/src/sim.rs
Fixes #253.
It occurs to me that, while blake2b is known to be fast in bulk operation, our branching byte-at-a-time use case is unusual and might not be well studied/optimized for. Could be worth benchmarking and experimenting with other hash functions (maybe including less cryptographic ones) but this is probably not the worst place to start.
> Path-hashed node identifiers

- common/src/worldgen.rs
- server/src/sim.rs
Minor simplification and optimization.
Spawn point is now atop a small hill, requiring a slight altitude adjustment.
> Seed worldgen per-node RNG from node hash

- client/src/loader.rs
- common/src/chunk_collision.rs
- common/src/graph_collision.rs
- save/src/lib.rs
- server/src/sim.rs
This PR has two unrelated changes bundled together, as both need to be done for CI to accept this PR.
This fixes an error reported by `#[deny(clippy::incorrect_clone_impl_on_copy_type)]`:
```
error: incorrect implementation of `clone` on a `Copy` type
--> client\src\loader.rs:303:29
|
303 |       fn clone(&self) -> Self {
|  _____________________________^
304 | |         Self {
305 | |             table: self.table,
306 | |             index: self.index,
307 | |             _marker: PhantomData,
308 | |         }
309 | |     }
| |_____^ help: change this to: `{ *self }`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incorrect_clone_impl_on_copy_type
= note: `#[deny(clippy::incorrect_clone_impl_on_copy_type)]` on by default
```
I did try …
> Fix clone implementation to honor clippy lint and apply cargo fmt to let-else statements

- server/src/sim.rs
There is an `unwrap` error when setting `q` in `snapshot_node`, since it uses `graph_entities` as the source of truth of entities that exist, but `graph_entities` was never updated on entity removal.
> Fix server crash on client disconnect due to incomplete entity removal

- common/src/graph_entities.rs
```
warning: use of `or_insert_with` to construct default value
--> common\src\graph_entities.rs:23:40
|
23 |         let vec = self.map.entry(node).or_insert_with(Vec::new);
|                                        ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `or_default()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default
= note: `#[warn(clippy::unwrap_or_default)]` on by default
```
> Fix clippy warning unwrap_or_default

- common/src/graph.rs
Having `NodeId` be the global hash that is guaranteed to be consistent across the server and its clients allows simpler reasoning about code. The main downsides are
- It's 4 times larger, being a `u128` instead of a `u32` internally, which could potentially impact performance.
- The graph has to use a map instead of an array for its internal data representation, also potentially impacting performance.
The advantages are
- There is only one `NodeId`, removing ambiguity in discussions and in variable names etc.
- There is no risk of introducing bugs later on by accidentally assuming that a local `NodeId` means the same on the server and client.
I don't expect `NodeId`'s size to be the source of any bottlenecks, as each node is a large enough part of the data structure, that the handling of …
> Replace NodeId implementation with global hash

- client/src/graphics/draw.rs
- client/src/graphics/window.rs
- client/src/main.rs
- client/src/sim.rs
This allows the client's `Sim` to store a `SimConfig` without wrapping it in an `Option`. The main downside is that it slightly complicates `window.rs` and `draw.rs`, but such complication is likely temporary and would go away in a future refactor (such as if a "connecting" screen is created, diverting control flow earlier pre-ServerHello).
> Delay client Sim creation until server parameters are received

- server/src/sim.rs
This fixes a regression I introduced in 7b558b5448cea257d661ee728110a7a2ebcad553, where player's couldn't see which way other players were facing.
It's still a little tricky to see which way other players are facing because the origin of the player model is at the feet, but my understanding is that this model is a placeholder, so improving this doesn't need to be a priority.
> Fix issue where the server wasn't processing orientation info

- Cargo.toml
- client/Cargo.toml
- client/src/net.rs
- common/src/codec.rs
- server/Cargo.toml
- server/src/lib.rs
Update rustls from 0.20.6 to 0.21.7.
Update quinn from 0.8.3 to 0.10.2.
Most changes are simple compatibility fixes, mostly involving turning previously-quinn-provided streams into loops with task spawns.
One small but potentially important change is that the `ClientEvent::Lost` message will always be sent when an error occurs, even if the connection was already closed from some other logic and the client was already cleaned up. To be robust to this kind of redundancy and potential race conditions, the `on_client_event` method is set up to skip messages received from clients that were already cleaned up.
> Update quinn and rustls

- client/src/prediction.rs
- client/src/sim.rs
- common/benches/bench.rs
- common/src/character_controller/collision.rs
- common/src/character_controller/mod.rs
- common/src/cursor.rs
- common/src/graph.rs
- common/src/graph_collision.rs
- common/src/node.rs
- common/src/traversal.rs
- common/src/worldgen.rs
- server/src/sim.rs
Currently, outside of tests, the only implementation of `Graph` is `DualGraph`. This used to not be true, as the server used a `Graph<()>` instead, but to allow server-side collision checking, this has changed. In the spirit of only using generics when necessary, this PR gets rid of the `Graph`/`DualGraph` distinction.
As part of this change, this PR also attaches `ChunkLayout` data to `Graph`, as it arguably makes sense for this data to live together, but it was harder to do something like this cleanly when `Graph` was generic. This can enable additional helper methods, such as one that takes a `ChunkId` and a set of coordinates and alters corresponding voxel, taking care of adjacent chunk margins and surface invalidation (without needing to repeatedly pass in the dimension as a …
> Replace generic Graph with concrete implemetation and include ChunkLayout

- client/src/graphics/window.rs
- client/src/sim.rs
- common/src/character_controller/mod.rs
The ten materials that can be selected can be edited by changing the field material_palette in client/src/sim.rs.
The change in common/src/character_controller/mod.rs was necessary for the server not to crash when running on my machine.
As of now, the number keys map to the following materials:
1: Wood Planks
2: Grass
3: Dirt
4: Sand
5: Snow
6: White Brick
7: Grey Brick
8: Basalt
9: Water
0: Lava
> Allow for number keys to select type of block to be placed

- save/src/protos.proto
- save/src/protos.rs
- server/Cargo.toml
- server/src/postcard_helpers.rs
- server/src/sim.rs
Nodes are unlikely to ever have enough entities in them for column-major representation to be worth the trouble to implement. As a bonus, this representation should be compatible with postcard.
We can easily switch this up again in the future if needed thanks to protobuf schema evolution.
> Define a simpler row-major entity encoding for saves

- client/src/graphics/voxels/mod.rs
- client/src/sim.rs
- common/src/graph.rs
- common/src/node.rs
- common/src/proto.rs
- common/src/world.rs
- save/src/lib.rs
- server/src/lib.rs
- server/src/sim.rs
Whenever a block is updated, ensure that an updated version of the relevant node is written to the save file. When a world is initialized on the server-side, all modified chunks are loaded from the save file and stored in memory, to be retrieved whenever the relevant node is to be added to the graph.
This is a temporary implementation, as it does not properly scale for larger worlds, where we may not want to store all modified chunks in RAM.
Note that while this implements loading save data, it only loads voxels. Entity locations, such as the player's location, are ignored.
> Save and load all modified chunks

- server/src/sim.rs
This fixes a bug where if a client connects to the server before the server runs its first step, the player is in an unpopulated graph node when the character controller tries to run, causing a panic due to not knowing which way is upwards.
> Do graph node population before character movement

- client/src/local_character_controller.rs
- client/src/sim.rs
~This moves the viewpoint before applying orientation, so looking down is equivalent to face-planting, which isn't ideal.~ Adjusting the viewpoint by `Graph::get_relative_up` after rotation so the camera rotates in-place makes more sense, but suffers from sharp discontinuities when crossing between nodes, presumably due to relying on the discrete `NodeState::up_direction`. We should come up with a properly smooth notion of "up".
> Move camera to the top of the player's collider

- client/src/graphics/base.rs
- client/src/graphics/voxels/surface_extraction.rs
Aarch64 Linux has [`c_char` as `u8` rather than `i8`](https://doc.rust-lang.org/1.75.0/src/core/ffi/mod.rs.html#99) as the code expects. This fixes the build there.
> Use `c_char` instead of `i8` where necessary

- client/shaders/fog.frag
This PR hijacks the fog shader to also add a cursor in the center of the viewport to allow players to target where they place and break blocks.
This introduces an `if` statement to the fragment shader, and branching in shaders is generally bad for performance in my understanding, but given its simplicity, I believe that the shader compiler should be smart enough to optimize this in a way that acts as though such branching basically does not exist.
> Add a cursor to make placing/breaking blocks easier

- shell.nix
> Added mozilla overlay and mold linker to shell.nix

- client/src/graphics/core.rs
A potential failure case that prevents Hypermine from loading is the use of Vulkan layers that violate the Vulkan specifications. To assist in debugging, we add the list of Vulkan instance layers to the console log while Hypermine is running.
While device layers may also exist, they have been deprecated for a long enough time that I'm hopeful we won't have to include these in the logs as well, although this does run the risk of a buggy device layer going unnoticed.
> Add the list of Vulkan instance layers to the log

- common/src/sim_config.rs
A faster tick rate reduces the lag between mouse clicks and the modification of terrain, which would be a good quality of life improvement, especially while prediction is not implemented for terrain modification.
> Use a simulation rate of 30 steps per second instead of 10

- client/Cargo.toml
- client/src/graphics/window.rs
winit now defaults to raw-window-handle 0.6, but ash-window is not yet compatible with this version of raw-window-handle. Fortunately, the `rwh_05` feature allows the use of the older version of raw-window-handle.
A few notable changes:
- winit did an overhaul of keyboard input, so the use of `virtual_keycode` had to be replaced with `physical_key` or `logical_key`. I guessed that `physical_key` was better.
- `Event::MainEventsCleared` was removed from winit, so I needed to switch to `AboutToWait`. However, I used https://github.com/rust-windowing/winit/blob/7bed5eecfdcbde16e5619fd137f0229e8e7e8ed4/examples/request_redraw.rs as an example, which had me make the additional change of putting all the frame logic in `WindowEvent::RedrawRequested` and using `self.window.request_redraw` in …
> Update winit to 0.29.10

- client/Cargo.toml
- server/Cargo.toml
Based on https://github.com/rustls/rcgen/blob/main/rcgen/CHANGELOG.md, `ring` was made into an optional dependency with `aws-lc-rs` as an alternative choice. The create now requires either `ring` or `aws-lc-rs` to be specified as a feature (with `ring` as a default feature).
To be consistent with previous functionality, this PR uses `ring`.
> Update rcgen to 0.12.1

- client/Cargo.toml
- client/src/graphics/draw.rs
- client/src/graphics/voxels/mod.rs
- client/src/metrics.rs
This PR was mainly created by comparing https://github.com/metrics-rs/metrics/blob/metrics-v0.21.1/metrics/examples/basic.rs to https://github.com/metrics-rs/metrics/blob/metrics-v0.22.1/metrics/examples/basic.rs whenever there were compiler errors.
> Update metrics crate to 0.22.1

- .github/dependabot.yml
This PR stops dependabot from checking for updates of `raw-window-handle`, `rustls`, and `rustls-pemfile` because updates to these crates have to be done in tandem with upgrades to other crates (namely `ash-window` and `quinn`).
> Stop dependabot from updating packages that likely cannot be updated

- save/Cargo.toml
- save/benches/bench.rs
- save/src/lib.rs
- save/tests/heavy.rs
- save/tests/tests.rs
- server/src/sim.rs
This change breaks save file compatibility.
> Update redb to 2.0

- common/src/cursor.rs
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/node.rs
- common/src/worldgen.rs
- server/src/sim.rs
> Replace .iter().copied() on arrays with .into_iter()

- common/Cargo.toml
- common/src/cursor.rs
- common/src/dodeca.rs
> Replace lazy_static! with OnceLock

- client/src/config.rs
- client/src/main.rs
Having the ability to choose which save file is active would allow me to swap between them when, for instance, trying out different chunk sizes or switching between an older and newer version of Hypermine. It would also make it easier to test save files on an HDD to make sure that doesn't become an important bottleneck.
Fortunately, it looks like the implementation for this is quite simple. I chose to call the configuration option `save` for consistency with the server. If you give it a full path, it will save at that path, but if you give it a partial path, it will save in the data directory. All of this functionality comes for free with the `PathBuf::join` function.
> Make saves configurable for the client

- client/shaders/surface-extraction/extract.comp
- client/src/sim.rs
- common/src/chunk_collision.rs
- common/src/chunk_ray_casting.rs
- common/src/dodeca.rs
- common/src/graph_collision.rs
- common/src/graph_ray_casting.rs
- common/src/lib.rs
- common/src/margins.rs
- common/src/node.rs
- common/src/proto.rs
- common/src/voxel_math.rs
- common/src/worldgen.rs
Fixes #41 (Although ambient occlusion won't be 100% accurate due to ignored edge ~and corner~ margins)
Fixes #330 (Necessary to avoid noticeable z-fighting after this change)
This PR ensures that the chunk margins that affect which surfaces are extracted are accurate, ensuring that no surfaces between two solid voxels are rendered, which should result in better draw performance and a clearer view when no-clipping beneath the terrain.
After a chunk is ready to be added to the world (which could be from terrain generation, loading saves, or downloading chunks from a server), the margins of that chunk and its adjacent chunks are modified to be consistent with each other. Then, whenever a block update occurs, margins in adjacent chunks are updated to be consistent with that block update.
To …
> Implement accurate margins between adjacent chunks

- client/src/graphics/voxels/mod.rs
- client/src/sim.rs
- common/benches/bench.rs
- common/src/graph_collision.rs
- common/src/margins.rs
- common/src/node.rs
- common/src/voxel_math.rs
- server/src/sim.rs
This PR fixes two bugs related to https://github.com/Ralith/hypermine/pull/379.
Some of the logic assumed that world generation would never create "solid" chunks unless it was sure that the chunk was deep enough underground or high enough up in the air to not touch any surfaces. This assumption allowed us to avoid reconciling margins between a solid chunk and a dense chunk unless the dense chunk was "modified".
However, since this assumption was incorrect (for instance, due to world generation not turning solid "void" chunks into dense chunks unless a voxel is actually generated), this produced gaps in the terrain whenever a dense chunk met a solid void chunk.
When a voxel is modified, we assumed that only neighboring chunks' margins needs to update, since all other margins should already …
> Fix inconsistencies with margin reconciliation logic

- client/src/graphics/voxels/mod.rs
- common/src/traversal.rs
The `math::distance` normalizes the input vectors as part of its computation, which results in a loss of precision when an input vector is large.
For situations where that matters, such as in `traversal.rs`, we use `math::mip` instead of `math::distance`. Note that, when the input vectors are already pre-normalized, the distance formula simplifies to `(-mip(a, b)).acosh()`, which is likely small enough to not need its own function.
Note that the actual bug this fixes is that distance computations in `traversal::ensure_nearby` were resulting in `NaN`, which caused the loop to continue on forever, continuing to expand out the graph until running out of memory.
> Bugfix: Remove unintended view distance limit

- client/src/graphics/draw.rs
- client/src/graphics/voxels/mod.rs
- client/src/metrics.rs
- client/src/sim.rs
This PR tries to grab some of the low hanging fruit for ways to improve CPU performance for larger render distances. Based on profiling I've done on my end, these are likely the easiest performance improvements we can make, and larger performance improvements would likely require more work.
This PR has two changes to make metrics easier to use and two changes that improve performance:
Metrics:
- Metrics are sorted before being displayed.
- Profiling doesn't begin until the server has sent at least one node to the client.
Performance:
- The results of `traversal::nearby_nodes` are reused so that they only have to run once per frame
- The logic to start generating new chunks is skipped if the work queue is full.
As for what this did, here are some very rough metrics for a render distance of …
> Simple optimizations

- client/src/graphics/core.rs
Rust 1.78.0 introduced some debug assertions for unsafe preconditions. One such precondition, which we have inadvertently violated for a while was that `slice::from_raw_parts` does not accept null pointers, even when the size is 0.
An except from the Rust docs:
> `data` must be non-null and aligned even for zero-length slices. One reason for this is that enum layout optimizations may rely on references (including slices of any length) being aligned and non-null to distinguish them from other data. You can obtain a pointer that is usable as `data` for zero-length slices using `NonNull::dangling`.
While another option could have been to replace `ptr` with `NonNull::dangling` if it was null, simply handling this case separately seems like a simpler approach.
This is the error that appeared …
> Handle null pointer in fmt_labels

- client/src/graphics/base.rs
These account for one of the errors reported in https://github.com/Ralith/hypermine/issues/390. I don't see the others on my laptop, but I may try another machine.
> Fix depth buffer sync

- .github/workflows/package.yml
Packaging has little value as CI, and is slow.
> Don't package PRs

- client/src/graphics/draw.rs
- client/src/graphics/voxels/surface_extraction.rs
> Fix remaining sync issues

- client/Cargo.toml
- client/shaders/fog.frag
- client/src/graphics/base.rs
- client/src/graphics/core.rs
- client/src/graphics/draw.rs
- client/src/graphics/gui.rs
- client/src/graphics/mod.rs
- client/src/graphics/window.rs
- client/src/sim.rs
This PR adds a GUI with the following features:
- A central cursor
- Some indicator (likely textual) of the block you have selected
- The ability to turn it on and off (for screenshot purposes) with F1
> Add a basic GUI to Hypermine powered by yakui

- client/src/graphics/meshes.rs
- client/src/graphics/window.rs
- client/src/lahar_deprecated/transfer.rs
- client/src/prediction.rs
- common/src/lru_slab.rs
- server/src/lib.rs
This PR fixes the following two lints:
* `clippy::legacy_numeric_constants`
* `clippy::missing_transmute_annotations`
> Fix clippy lints for Rust 1.79

- client/src/graphics/gui.rs
- client/src/sim.rs
- common/src/node.rs
- common/src/proto.rs
- common/src/sim_config.rs
- server/src/lib.rs
- server/src/sim.rs
Partial fix for #397
This PR adds the initial version of an inventory component for players to store blocks they break. The following features exist:
- An ability to turn itself on and off, controlled by the `gameplay_enabled` sim_config property
- The GUI that tells you the quantity of the selected material you have. Since not all materials are selectable yet, if you break an unselectable material, it effectively disappears into the void.
- A server-authoritative inventory that gets synchronized with the client
The following features are left to future work:
- The ability to select any material you have on you
- A GUI that shows you everything you're holding at once
- Serialization of the inventory for saving
- Prediction of inventory contents (Required for the player to be able to place …
> Player inventory (initial version)

- .github/workflows/package.yml
An update to the shaderc-sys crate from 0.7 to 0.8 added a requirement to be able to view the vk.xml file to gather information about the installed version of Vulkan. To fix the workflow, we need to include that file in the list of files being extracted.
In addition, the cache action was upgraded from v2 to v4 because the old one was broken with errors like the following:
```
C:/VulkanSDK/1.3.231.1/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1'
```
> Fix issues with Windows package workflow

- client/src/sim.rs
- common/src/graph.rs
This PR accomplishes a few things, all in the spirit of hopefully reducing the mental load of understanding all the algorithms that allow `Graph` to grow:
- The term "parent" no longer depends on the graph's generation order. It now refers to the node along the first descender in enum order.
- Uses of the term "parent" and "child" were removed whenever they didn't refer to the above meaning of "parent". This includes renaming `insert_child` to `insert_neighbor` and renaming `populate_shorter_neighbors_of_child` to `populate_shorter_neighbors_of_subject` (where "subject" is a term that was introduced internally for "the neighbor node we want to insert" to try to improve clarity).
- An unused code path was removed in `ensure_neighbor` to cover the impossible scenario of a not-yet-generated …
> Simplify and document expansion functions of Graph

- client/src/net.rs
- common/src/math.rs
- common/src/proto.rs
- save/src/lib.rs
- server/src/lib.rs
- server/src/sim.rs
This PR sets up the initial implementation of loading entity data from a save file by loading player characters. In single-player, this has the effect of having the game remember where you were when you close it. If you change your name, you will spawn in as a new character.
The following are not currently implemented:
* Saving client-authoritative orientation data (the orientation quaternion)
* Only loading entities in nearby chunks (Currently, everything is loaded.)
* Saving the inventory
> Load character entities from the save file

- server/src/sim.rs
Before this commit, if `snapshot` was called before the server ran its first step, there would be some unpopulated nodes in the graph, resulting in such nodes being transmitted to the client twice, once during the call to `snapshot`, and once as an accumulated change when calling `step`.
This PR ensures that such an inconsistent state no longer occurs.
> Ensure the server state is consistent whenever snapshot is called

- client/Cargo.toml
- client/src/graphics/window.rs
- client/src/lib.rs
- client/src/main.rs
- client/src/net.rs
- client/src/sim.rs
- common/src/proto.rs
- server/Cargo.toml
- server/src/lib.rs
- server/src/main.rs
Towards https://github.com/Ralith/hypermine/issues/405.
Rough in some places ~and not actually working correctly yet~.
> In-process server

- save/gen-protos/Cargo.toml
- save/src/protos.rs
- server/src/sim.rs
This fixes a bug I introduced in PR #414 that likely only wasn't noticed because, in the current state of the game, entities are rarely destroyed.
Error:
```
thread '<unnamed>' panicked at server\src\sim.rs:407:64: 
called `Result::unwrap()` on an `Err` value: NoSuchEntity
```
> Don't crash when placing blocks with gameplay enabled

- client/src/graphics/voxels/surface_extraction.rs
- common/src/plane.rs
The lints in question are
- [clippy::manual_c_str_literals](https://rust-lang.github.io/rust-clippy/master/index.html#manual_c_str_literals)
- [clippy::manual_div_ceil](https://rust-lang.github.io/rust-clippy/master/index.html#manual_div_ceil)
- [clippy::needless_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes)
> Fix clippy lint warnings for Rust 1.83

- common/src/world.rs
- save/src/protos.proto
- save/src/protos.rs
- server/src/sim.rs
This completes part of #428.
Allows users to exit and re-open Hypermine while keeping the contents of their inventory, as previously, the inventory was cleared every time the game was loaded.
> Serialize the player's inventory in save files

- client/src/graphics/gltf_mesh.rs
- client/src/sim.rs
- common/src/graph.rs
Resolve all instances of the clippy lint [unnecessary_map_or](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or)
> Resolve clippy lints for Rust 1.84.0

- client/Cargo.toml
- common/Cargo.toml
- common/src/lib.rs
- common/src/worldgen.rs
- save/Cargo.toml
- save/benches/bench.rs
- save/tests/heavy.rs
- save/tests/tests.rs
- server/Cargo.toml
- server/src/sim.rs
This PR updates the following packages:
- rand
- rand_pcg
- rand_distr
- yakui
- yakui-vulkan
- tokio
- whoami
- webpki
Note that yakui released 0.3.0 recently, allowing us to use it as a cargo dependency instead of a github dependency.
The `nalgebra` package has not yet updated rand, so to avoid conflicts, I have removed the `rand` feature from `nalgebra` for now, replacing a call of `na::Vector3::from_distribution` with a call to `na::Vector3::from_fn` instead.
> Update packages to their latest versions

- common/src/cursor.rs
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/plane.rs
- server/src/sim.rs
Fixes #381
This PR makes the following changes to the `dodeca` module:
- `LazyLock` is used instead of `OnceLock` (This change is also made in cursor.rs)
- `Side` and `Vertex` have a `VALUES` array allowing for easier conversion between integers and enum values
- `VERTEX_COUNT` and `SIDE_COUNT` have been replaced with `Vertex::COUNT` and `Side::COUNT`
- `Vertex::from_sides` now takes in an array instead of 3 separate parameters for consistency with `Vertex::canonical_sides`
- Arrays are now initialized to their final values when it makes sense to do so (instead of being initialized to a dummy value and then filled in). This utilizes `array::from_fn` and `array::map` in various places.
- Complicated math is better explained in code comments
- Some implementations are replaced with simpler …
> Document and refactor dodeca.rs

- client/src/graphics/draw.rs
- client/src/graphics/frustum.rs
- client/src/graphics/voxels/mod.rs
- client/src/local_character_controller.rs
- client/src/sim.rs
- common/Cargo.toml
- common/src/character_controller/collision.rs
- common/src/character_controller/mod.rs
- common/src/chunk_collision.rs
- common/src/chunk_ray_casting.rs
- common/src/collision_math.rs
- common/src/dodeca.rs
- common/src/graph_collision.rs
- common/src/math.rs
- common/src/node.rs
- common/src/plane.rs
- common/src/sim_config.rs
- common/src/worldgen.rs
- server/src/sim.rs
This PR makes the following changes to the `math` module:
- Functions have been re-ordered for simplicity (separated to a different commit for diff readability)
- `simba` has been added as a direct dependency so that `to_f32` and `to_f64` can be combined into a single `cast` function (separated to a different commit because of the extra dependency)
- Rustdoc comments are added to `MVector` and `MIsometry` structs and functions that could benefit from them.
- Code comments are added inside functions with complicated implementations to better explain them.
- A few functions like `as_ref` and `row` are modified to better match their `nalgebra` counterparts (with fewer copies)
- Functions that create an `MIsometry` are moved into `MIsometry` (instead of being free functions, or, in the case …
> Document and simplify math module

- client/src/graphics/frustum.rs
- client/src/graphics/voxels/mod.rs
- client/src/sim.rs
- common/src/character_controller/collision.rs
- common/src/chunk_collision.rs
- common/src/chunk_ray_casting.rs
- common/src/collision_math.rs
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/graph_collision.rs
- common/src/margins.rs
- common/src/math.rs
- common/src/node.rs
- common/src/plane.rs
- common/src/sim_config.rs
- common/src/traversal.rs
- common/src/worldgen.rs
Fixes #264
Introduce two new unit vector types for `MVector`:
- `MPoint`
- `MDirection`
`MPoint` has the constraint `v.mip(v) == -1`, while `MDirection` has the constraint `v.mip(v) == 1`. Every method signature requiring an `MVector` with one of these constraints has been updated to take one of these more constrained types to reduce the chance of mistakes.
> Introduce two new unit vector types for MVector

- client/src/graphics/frustum.rs
- common/src/lib.rs
- common/src/math.rs
- common/src/plane.rs
- common/src/terraingen.rs
- common/src/worldgen.rs
Fixes #102
This PR repurposes plane.rs to serve primarily as the ground plane in worldgen, with the extra logic suggested in #102 (with some minor changes) to handle situations in which the ground plane is far from the origin. The main differences or possible surprises are as follows:
- The normal vector is represented as `scaled_normal * e^exponent` instead of `scaled_normal * 2^exponent`. (a base of `e` instead of 2)
- The exponent is a floating point number instead of an integer. This reduces the amount of casting needed.
- The magnitude of the normal vector is estimated by taking the absolute value of the w-coordinate, as for large enough vectors, the magnitude is proportional to that value.
- The exponent is only updated when the vector becomes very large in magnitude (instead of …
> Improve numerical stability of ground plane distance estimation

- client/src/graphics/draw.rs
- client/src/graphics/voxels/mod.rs
- client/src/graphics/window.rs
- client/src/lib.rs
- client/src/sim.rs
- client/src/worldgen_driver.rs
Uncoupling world generation from world rendering will be useful to allow flexibility in multiple areas in the future:
* The client's handling of world generation can stick entirely to safe Rust, making it easier to work with for newer contributors.
* The view distance and chunk generation distance can be kept separate, making it easier to find a resolution for #50 without killing performance or creating thick fog (as the user can then opt in or opt out of chunk pop-in).
* Once the client no longer fully relies on the server to decide which nodes should be generated, `WorldgenDriver` can be responsible for deciding how to expand the graph in addition to how to fill out its chunk data.
* Regarding graph traversal, `WorldgenDriver`'s FPS footprint can be reduced by spreading out graph …
> Uncouple client worldgen from rendering

- client/src/graphics/draw.rs
- client/src/graphics/voxels/mod.rs
- client/src/prediction.rs
- client/src/sim.rs
- client/src/worldgen_driver.rs
- common/benches/bench.rs
- common/src/dodeca.rs
- common/src/graph.rs
- common/src/graph_collision.rs
- common/src/margins.rs
- common/src/node.rs
- common/src/sim_config.rs
- common/src/traversal.rs
- common/src/worldgen.rs
- server/src/sim.rs
Note: The first few (2 as of the time I'm writing this) commits match https://github.com/Ralith/hypermine/pull/452, so this PR effectively branches off of https://github.com/Ralith/hypermine/pull/452, and only the later commits should be reviewed.
Since keeping the server and client graphs entirely in sync is one of the main reasons `Graph` needed to keep track of its freshly created nodes, and now they no longer need to be in sync this way, this PR removes this functionality to simplify `Graph`'s usage. Specifically, each `Node` is initialized immediately when it's added to the graph instead of being initialized to `None`. The `NodeState` field, which is used in fewer places, is still kept optional, and instead of being populated for every fresh node, it is populated for a given `NodeId` …
> Refactor graph expansion to remove the concept of "fresh" nodes

- .github/workflows/package.yml
The Package/Linux workflow is currently failing on master, being auto-cancelled with the following error:
> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
> Fix package-linux workflow by removing unsupported Ubuntu 20.04

- client/src/graphics/voxels/mod.rs
- common/src/graph.rs
- common/src/node.rs
- common/src/worldgen.rs
- server/src/sim.rs
The term "depth" is arguably more intuitive when expressing how far away from the root a graph's node is, so this should hopefully reduce the barrier to entry for learning the Hypermine codebase.
As for "parent", previously, it was often interpreted as though every node (except the root) has one parent, even though most logic took all "shorter neighbors" into account, so "parent" now refers to any neighbor node closer to the root. The old meaning of parent is renamed to "primary parent", which is the parent with the first side in enum order.
Given that I hope to add the new terminology of "peer" nodes into the code base, I think it makes sense to rethink existing terms to make sure they're consistent with each other and with what one might expect. I would like to rename some of the …
> Rename "length" to "depth" and make "parent" more useful
